org.gradle.jvmargs=-Xmx1024M
org.gradle.parallel=true
org.gradle.configuration-cache=false

version=0.159.0
minecraft_version=26.2
loader_version=0.18.4
installer_version=1.0.1

prerelease=false
curseforge_minecraft_versions=26.2
modrinth_extra_minecraft_versions=

# Do not manually update, use the bumpversions task:
fabric-api-base-version=2.0.4
fabric-api-lookup-api-v1-version=2.0.18
fabric-biome-api-v1-version=18.0.6
fabric-block-api-v1-version=3.0.3
fabric-block-getter-api-v2-version=2.0.7
fabric-client-gametest-api-v1-version=6.0.1
fabric-command-api-v2-version=3.1.0
fabric-content-registries-v0-version=11.3.2
fabric-crash-report-info-v1-version=1.0.5
fabric-data-attachment-api-v1-version=2.2.18
fabric-data-generation-api-v1-version=25.5.1
fabric-debug-api-v1-version=1.0.2
fabric-dimensions-v1-version=5.1.12
fabric-entity-events-v1-version=5.0.5
fabric-events-interaction-v0-version=5.2.7
fabric-game-rule-api-v1-version=4.0.8
fabric-gametest-api-v1-version=4.0.21
fabric-item-api-v1-version=14.5.0
fabric-creative-tab-api-v1-version=5.0.14
fabric-key-mapping-api-v1-version=2.0.5
fabric-lifecycle-events-v1-version=4.1.4
fabric-loot-api-v3-version=3.0.17
fabric-message-api-v1-version=7.0.8
fabric-model-loading-api-v1-version=8.0.17
fabric-networking-api-v1-version=6.3.3
fabric-object-builder-api-v1-version=24.1.0
fabric-particles-v1-version=5.0.18
fabric-permission-api-v1-version=1.0.5
fabric-recipe-api-v1-version=9.0.21
fabric-registry-sync-v0-version=7.1.0
fabric-renderer-api-v1-version=14.1.4
fabric-renderer-indigo-version=9.1.4
fabric-rendering-fluids-v1-version=6.0.4
fabric-rendering-v1-version=25.3.3
fabric-resource-conditions-api-v1-version=6.1.0
fabric-resource-loader-v0-version=3.3.20
fabric-resource-loader-v1-version=2.0.13
fabric-screen-api-v1-version=5.2.1
fabric-menu-api-v1-version=2.0.16
fabric-serialization-api-v1-version=2.0.4
fabric-sound-api-v1-version=2.0.5
fabric-tag-api-v1-version=2.1.4
fabric-transfer-api-v1-version=8.0.13
fabric-transitive-access-wideners-v1-version=8.1.4
fabric-convention-tags-v2-version=4.7.1
