version = getSubprojectVersion(project)

loom {
	accessWidenerPath = file('src/client/resources/fabric-client-gametest-api-v1.classtweaker')
}

moduleDependencies(project, [
	':fabric-networking-api-v1'
])

sourceSets {
	mixinConfig {
		compileClasspath += configurations.loaderLibraries
	}
	client {
		compileClasspath += mixinConfig.output
		runtimeClasspath += mixinConfig.output
	}
}

configurations {
	clientImplementation.extendsFrom mixinConfigImplementation
	clientRuntimeOnly.extendsFrom mixinConfigRuntimeOnly
}

dependencies {
	mixinConfigImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

jar {
	from sourceSets.mixinConfig.output
}
