plugins {
	id 'fabric-api.module'
}

loom {
	accessWidenerPath = file("src/main/resources/fabric-registry-sync-v0.classtweaker")
}

fabricApiModule {
	moduleDependencies(
		'fabric-api-base',
		'fabric-networking-api-v1'
	)

	testDependencies(
		':fabric-lifecycle-events-v1',
		':fabric-command-api-v2',
		':fabric-client-gametest-api-v1'
	)
}
