import java.nio.file.Files

for (def sourceSet in [
			sourceSets.main,
			sourceSets.client
		]) {
	// We have to capture the source set name for the lazy string literals,
	// otherwise it'll just be whatever the last source set is in the list.
	def sourceSetName = sourceSet.name
	def generateTask = tasks.register(sourceSet.getTaskName('generate', 'PackageInfos'), GeneratePackageInfos) {
		group = 'fabric'
		description = "Generates package-info files for $sourceSetName packages."

		// Only apply to default source directory since we also add the generated
		// sources to the source set.
		sourceRoot = file("src/$sourceSetName/java")
		header = rootProject.file('HEADER')
		outputDir = file("src/generated/$sourceSetName")
	}
	sourceSet.java.srcDir generateTask
	ideaSyncTask.dependsOn generateTask

	def cleanTask = tasks.register(sourceSet.getTaskName('clean', 'PackageInfos'), Delete) {
		group = 'fabric'
		delete file("src/generated/$sourceSetName")
	}
	clean.dependsOn cleanTask
}

abstract class GeneratePackageInfos extends DefaultTask {
	@InputFile
	File header

	@Input
	abstract Property<String> getProjectName()

	@SkipWhenEmpty
	@InputDirectory
	final DirectoryProperty sourceRoot = project.objects.directoryProperty()

	@OutputDirectory
	final DirectoryProperty outputDir = project.objects.directoryProperty()

	GeneratePackageInfos() {
		projectName.set(project.name)
	}

	@TaskAction
	def run() {
		def output = outputDir.get().asFile.toPath()
		output.deleteDir()
		def headerText = header.readLines().join("\n") // normalize line endings
		def root = sourceRoot.get().asFile.toPath()

		root.eachDirRecurse {
			def containsJava = Files.list(it).withCloseable { stream ->
				stream.any {
					Files.isRegularFile(it) && it.fileName.toString().endsWith('.java')
				}
			}

			if (!containsJava) {
				return
			}

			def relativePath = root.relativize(it)
			def target = output.resolve(relativePath)
			def packageName = relativePath.toString().replace(File.separator, '.')
			def implPattern = /^(net[\/\\]fabricmc[\/\\]fabric[\/\\](impl|mixin))/
			def isImpl = relativePath.toString() =~ implPattern

			if (packageName == "net.fabricmc.fabric.api.util" && projectName.get() == "fabric-content-registries-v0") {
				// Hack: This package clashes with api-base, don't generate any annotations for it.
				return
			}

			// Check existing explicit package-info.java to ensure it has @NullMarked / @ApiStatus.Internal
			def existingPackageInfo = it.resolve('package-info.java')
			if (Files.exists(existingPackageInfo)) {
				def text = existingPackageInfo.text

				if (!text.contains("@NullMarked")) {
					throw new RuntimeException("package-info.java ${existingPackageInfo} is missing @NullMarked annotation.")
				} else if (isImpl && !text.contains("@ApiStatus.Internal")) {
					throw new RuntimeException("Impl package-info.java ${existingPackageInfo} is missing @ApiStatus.Internal annotation.")
				}

				return
			}

			Files.createDirectories(target)
			target.resolve('package-info.java').withWriter {
				if (isImpl) {
					it.write("""$headerText
						|/**
						| * Implementation code for ${projectName.get()}.
						| */
						|@ApiStatus.Internal
						|@NullMarked
						|package $packageName;
						|
						|import org.jetbrains.annotations.ApiStatus;
						|import org.jspecify.annotations.NullMarked;
						|""".stripMargin())
				} else {
					it.write("""$headerText
						|/**
						| * API code for ${projectName.get()}.
						| */
						|@NullMarked
						|package $packageName;
						|
						|import org.jspecify.annotations.NullMarked;
						|""".stripMargin())
				}
			}
		}
	}
}
