import net.fabricmc.fabric.impl.build.AbstractGenerateClassTweakerTask

import org.gradle.api.tasks.TaskAction
import org.objectweb.asm.Opcodes
import org.objectweb.asm.tree.ClassNode

import java.lang.reflect.Modifier

plugins {
	id 'fabric-api.module'
}

fabricApiModule {
	moduleDependencies(
		'fabric-convention-tags-v2',
		'fabric-recipe-api-v1',
		'fabric-registry-sync-v0',
		'fabric-resource-conditions-api-v1',
		'fabric-tag-api-v1',
	)

	testDependencies(
		':fabric-creative-tab-api-v1',
		':fabric-loot-api-v3',
		':fabric-object-builder-api-v1'
	)
}

dependencies {
}

sourceSets {
	testmod {
		resources {
			srcDirs += [
				'src/testmod/generated'
			]
		}
	}
}

loom {
	accessWidenerPath = file("src/main/resources/fabric-data-generation-api-v1.classtweaker")

	runs {
		datagen {
			inherit testmodServer
			displayName = "Data Generation"
			systemProperties.put("fabric-api.datagen", "")
			systemProperties.put("fabric-api.datagen.output-dir", "${file("src/testmod/generated")}")
			systemProperties.put("fabric-api.datagen.strict-validation", "")

			generateRunConfig = true
			runDirectory = file("build/datagen")
		}
		datagenClient {
			client()
			displayName = "Data Generation Client"
			systemProperties.put("fabric-api.datagen", "")
			systemProperties.put("fabric-api.datagen.output-dir", "${file("src/testmod/generated")}")
			systemProperties.put("fabric-api.datagen.strict-validation", "")

			generateRunConfig = true
			runDirectory = file("build/datagen")
			sourceSet = sourceSets.testmodClient.name
		}
	}
}

runDatagen {
	outputs.dir file("src/testmod/generated")
}

runDatagenClient {
	outputs.dir file("src/testmod/generated")
}

tasks.register('datapackZip', Zip) {
	archiveFileName = "${base.archivesName.get()}-${project.version}-test-datapack.zip"
	destinationDirectory = layout.buildDirectory.dir('libs')

	from file("src/testmod/generated")
	from file("pack.mcmeta")
}

build.dependsOn datapackZip

abstract class GenerateDataClassTweakerTask extends AbstractGenerateClassTweakerTask {
	@TaskAction
	void run() {
		def classes = readClasses()
		def task = this
		List<String> lines = new ArrayList<>()
		addHeader(lines, "classTweaker\tv1\tofficial", true)

		visitMethods(classes.get("net/minecraft/data/recipes/RecipeProvider")) { method, owner ->
			if (method.name == "generate") {
				return
			}

			task.addMethod(lines, "transitive-accessible", owner, method)
		}

		visitMethods(classes.get("net/minecraft/client/data/models/BlockModelGenerators")) { method, owner ->
			if (method.desc == "()V") {
				return
			}

			task.addMethod(lines, "transitive-accessible", owner, method)
		}

		visitStaticFinalFields(classes.get("net/minecraft/client/data/models/BlockModelGenerators")) { field, owner ->
			if (field.desc == "Lnet/minecraft/client/data/models/blockstates/PropertyDispatch;") {
				lines.add("transitive-accessible\tfield\t${owner}\t${field.name}\t${field.desc}")
			}
		}

		visitMethods(classes.get("net/minecraft/data/loot/BlockLootSubProvider")) { method, owner ->
			task.addMethod(lines, "transitive-accessible", owner, method)
		}

		visitMethods(classes.get("net/minecraft/client/data/models/ItemModelGenerators")) { method, owner ->
			task.addMethod(lines, "transitive-accessible", owner, method)
		}

		classes.values().forEach { classNode ->
			visitFinalMethods(classNode) { method, owner ->
				if (method.name != "getName" || method.desc != "()Ljava/lang/String;") {
					return
				}

				if (!task.hasAncestor(classNode, classes, "net/minecraft/data/DataProvider")) {
					return
				}

				task.addMethod(lines, "transitive-extendable", owner, method)
			}
		}

		writeOutput(lines)
	}

	void addMethod(List<String> lines, String access, String owner, method) {
		lines.add("${access}\tmethod\t${owner}\t${method.name}\t${method.desc}")
	}

	void visitMethods(ClassNode classNode, Closure visitor) {
		classNode.methods.forEach { method ->
			if ((method.access & Opcodes.ACC_SYNTHETIC) != 0 || (method.access & Opcodes.ACC_PUBLIC) != 0) {
				return
			}

			if (method.name.startsWith("<")) {
				return
			}

			visitor(method, classNode.name)
		}
	}

	void visitFinalMethods(ClassNode classNode, Closure visitor) {
		classNode.methods.forEach { method ->
			if (!Modifier.isFinal(method.access)) {
				return
			}

			if (method.name.startsWith("<")) {
				return
			}

			visitor(method, classNode.name)
		}
	}

	void visitStaticFinalFields(ClassNode classNode, Closure visitor) {
		classNode.fields.forEach { field ->
			int access = Opcodes.ACC_STATIC | Opcodes.ACC_FINAL

			if ((field.access & access) != access || (field.access & Opcodes.ACC_PUBLIC) != 0) {
				return
			}

			visitor(field, classNode.name)
		}
	}

	boolean hasAncestor(ClassNode classNode, Map<String, ClassNode> classes, String ancestorName) {
		if (classNode.superName == ancestorName) {
			return true
		}

		def superClass = classes.get(classNode.superName)

		if (superClass != null && hasAncestor(superClass, classes, ancestorName)) {
			return true
		}

		for (String interfaceName : classNode.interfaces) {
			if (interfaceName == ancestorName) {
				return true
			}

			def ifaceClass = classes.get(interfaceName)

			if (ifaceClass != null && hasAncestor(ifaceClass, classes, ancestorName)) {
				return true
			}
		}

		return false
	}
}

tasks.register('generateClassTweaker', GenerateDataClassTweakerTask) {
	template = file("template.classtweaker")
	outputFile = file("src/main/resources/fabric-data-generation-api-v1.classtweaker")
}

generateResources.dependsOn generateClassTweaker
generateResources.dependsOn runDatagenClient
processResources.mustRunAfter generateClassTweaker
